//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videogames_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desarrolladora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desarrolladora()
        {
            this.Games = new HashSet<Games>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string País { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Games> Games { get; set; }

        public static implicit operator Desarrolladora(DesarrolladoraDTO v)
        {
            throw new NotImplementedException();
        }
    }
}
