//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videogames_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Gènere { get; set; }
        public System.DateTime Release { get; set; }
        public int id_desarrolladora { get; set; }
        public Nullable<int> PEGI { get; set; }
        public Nullable<bool> PS4 { get; set; }
        public Nullable<bool> NSwitch { get; set; }
        public Nullable<bool> XboxOne { get; set; }
        public Nullable<bool> PC { get; set; }
    
        public virtual Desarrolladora Desarrolladora { get; set; }
    }
}
